<style  type="text/css">
cool {
  width: 100px;
  height: 100px;
  background-color: red;
  position: relative;
  -webkit-animation-name: example; /* Safari 4.0 - 8.0 */
  -webkit-animation-duration: 4s; /* Safari 4.0 - 8.0 */
  -webkit-animation-iteration-count: infinite; /* Safari 4.0 - 8.0 */
  animation-name: example;
  animation-duration: 4s;
  animation-iteration-count: infinite;
}

loud {
    font-size: 20pt;
    }

/* Safari 4.0 - 8.0 */
@-webkit-keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}

/* Standard syntax */
@keyframes example {
  0%   {background-color:red; left:0px; top:0px;}
  25%  {background-color:yellow; left:200px; top:0px;}
  50%  {background-color:blue; left:200px; top:200px;}
  75%  {background-color:green; left:0px; top:200px;}
  100% {background-color:red; left:0px; top:0px;}
}
</style>

<b><center>
<span style="font-size: 24pt; line-height: 1.2">
COMS W4111: Introduction to Databases<br>
Spring 2024, Sections 002/V02
</span>
</center></b>
<br>
<p>
<i><center>
<span style="font-size: 20pt; line-height: 1.2">
Homework 1<br>Introduction to Core Concepts, ER Modeling, Relational Algebra, SQL<br>
</span>
</center></i>

# Introduction

This notebook contains Homework 1. **Both Programming and Nonprogramming tracks should complete this homework.**

# Submission Instructions

- You will submit **PDF and ZIP files** for this assignment. Gradescope will have two separate assignments for these.
- For the PDF:
    - The most reliable way to save as PDF is to go to your browser's menu bar and click `File -> Print`. Switch the orientation to landscape mode, and hit save.
    - **MAKE SURE ALL YOUR WORK (CODE AND SCREENSHOTS) IS VISIBLE ON THE PDF. YOU WILL NOT GET CREDIT IF ANYTHING IS CUT OFF.** Reach out for troubleshooting.
    - **MAKE SURE YOU DON'T SUBMIT A SINGLE PAGE PDF.** Your PDF should have multiple pages.
- For the ZIP:
    - Zip a folder containing this notebook and any screenshots.
    - You may delete any unnecessary files, such as caches.

<hr style="height:2px;">

# Add Student Information

In [1]:
# Print your name, uni, and track below

name = "Usman Moazzam"
uni = "uam2105"
track = "Programming Track"

print(name)
print(uni)
print(track)

Usman Moazzam
uam2105
Programming Track

# Setup

## SQL Magic

The `sql` extension was installed in HW0. Double check that if this cell doesn't work.

In [2]:
%load_ext sql

You may need to change the password below.

In [3]:
%sql mysql+pymysql://root:dbuserdbuser@localhost

In [4]:
%sql SELECT * FROM db_book.student WHERE ID = 12345

 * mysql+pymysql://root:***@localhost
1 rows affected.

[('12345', 'Shankar', 'Comp. Sci.', Decimal('32'))]

## Python Libraries

In [5]:
from IPython.display import Image
import pandas

<hr style="height:2px;">

# Written Questions

Chapter 1 from the recommended textbook [Database System Concepts, Seventh Edition](https://codex.cs.yale.edu/avi/db-book/) covers general information and concepts about databases and database management systems. Lecturing on the general and background information is not a good use of precious class time. To be more efficient with class time, the chapter 1 information is a reading assignment.

Answering the written questions in HW 1, Part 1 does not require purchasing the textbook and reading the chapter. The [chapter 1 slides](https://codex.cs.yale.edu/avi/db-book/slides-dir/index.html) provided by the textbook authors provide the necessary information. In some cases, students may also have to search the web or other sources to “read” the necessary information.

When answering the written questions, do not “bloviate”. The quantity of words does not correlate with the quality of the answer. We will deduct points if you are not succinct. The answers to the questions require less than five sentences or bullet points.

### “If you can't explain something in a few words, try fewer.”

You may use external resources, but you should cite your sources.

## W1

What is a database management system and how do relational databases organize data?

**Answer:**

According to [Oracle](https://www.oracle.com/database/what-is-database/), a database management system, or DBMS, is a software tool used to create, organize, manipulate and retrieve data for end-users. Relational databases organize data into a set of tables with rows and columns, ensuring that the data is highly structured.

## W2

Columbia University uses several applications that use databases to run the university. Examples are SSOL and CourseWorks. An alternate approach could be letting students, faculty, administrators, etc. use shared Google Sheets to create, retrieve, update, and delete information. What are some problems with the shared spread sheet approach and what functions do DMBS implement to solve the problems?

**Answer:**

Using the shared spread sheet approach poses many challenges that would impact the accuracy, integrity, security and many other aspects of the applications' data, negatively impacting the function of the university. Listed below are distinct data considerations as well how they are managed/impact by spreadsheets and DBMS's.

* Accuracy/integrity: Most DBMS's enforce data integrity using strict structure, ensuring that the data remains accurate and consistent in its format and structure. Spreadsheets however do not provide strict structure or rules over data entry, resulting in high risk for human error
* Security: DBMS's can institute read/write permissions and other access controls to ensure that data remains secure and private, and only accessible by the appropriate entities. Spreadsheets on the other hand are easily shareable, risking the general privacy of the data and the individuals/entities that it describes
* Performance: DBMS's are optimized to handle and support large sets of data while maintaining high performance. Spreadsheets are not equipped with the same optimization, and often struggle when scaling to large datasets

Source: [365 Data Science](https://365datascience.com/tutorials/sql-tutorials/database-vs-spreadsheet/)

## W3

Explain the differences between SQL, MySQL Server and DataGrip.

**Answer:**

SQL (Structured Query Language) is a standardized language used to interact with relational databases, defining operations like querying and updating data. MySQL Server, an open-source relational database management system, implements SQL to store and manage data efficiently. It's widely adopted for its performance, reliability, and scalability. DataGrip, on the other hand, is an IDE tailored for SQL database development, offering features like code completion and schema visualization across various database management systems, including MySQL, PostgreSQL, and Oracle. While SQL is the language, MySQL Server is the database system, and DataGrip is the development environment for working with SQL databases.

Source: [SimpliLearn](https://www.simplilearn.com/tutorials/sql-tutorial/difference-between-sql-and-mysql)

## W4

Crow’s Foot Notation has four endings for relationship lines. Briefly explain the meaning of each ending.

<img src="./CFN.png">

**Answer:**

1. The first symbol denotes a cardinality of zero or one
2. The second symbol denotes a cardinality of one, and *only* one
3. The third symbol denotes a cardinality of zero, one, or many
4. The fourth symbol denotes a cardinality of one or many

Source: [Microsoft Support](https://support.microsoft.com/en-us/office/create-a-diagram-with-crow-s-foot-database-notation-1ec22af9-3bd3-4354-b2b5-ed5752af6769)

## W5

What is a primary key and why is it important?

**Answer:**

A primary key is a unique identifier for each record in a database table, ensuring data integrity and facilitating efficient data retrieval and manipulation. It prevents duplicate records, establishes relationships between tables, and enables reliable operations like data retrieval, updates, and deletion.

Source: Lecture

## W6

The relational algebra is closed under the operators. Explain what this means and give an example.

**Answer:**

This means that applying operations like SELECT, PROJECT, JOIN, etc to relations always produces valid relations as output. For instance, if we have a relation R and we perform a SELECT operation on it, the result will still be a relation. This property ensures that operations in relational algebra maintain consistency and validity, making it a foundational principle in relational database theory. It guarantees that relational algebra operations can be chained together without violating the rules of relational databases.

Source: [W3Schools](https://www.w3schools.in/dbms/relational-algebra)

## W7

Some of the Columbia University databases/applications represent the year/semester attribute of a section in the form "2023_2". The first four characters are the academic year, and the last character is the semester (1, 2, or 3). The data type for this attribute might be CHAR(6). Using this example, explain the concepts of domain and atomic domain. How is domain different from type?

**Answer:**

In this example, the domain represents the set of all possible values for the attribute "2023_2," including academic years and semesters. The atomic domain refers to the individual components within this set, such as the academic year and semester. 

The data type CHAR(6) specifies how the attribute's values are stored in memory, allowing for a fixed-length string of up to 6 characters. While the domain encompasses all possible values, the data type determines the physical representation of those values within the database.

Source: [Relational DB Design](https://www.relationaldbdesign.com/database-design/module5/attribute-domains-types.php)

## W8

Briefly explain the difference between a database schema and database instance.

**Answer:**

A database schema defines the structure and organization of a database, while a database instance refers to the actual data stored in the database at a particular moment.

Source: [Geeks For Geeks](https://www.geeksforgeeks.org/difference-between-schema-and-instance-in-dbms/)

## W9

Briefly explain the concepts of data definition language and data manipulation language.

**Answer:**

Data Definition Language (DDL) is used to define the structure and schema of a database, including creating, modifying, and deleting database objects such as tables, indexes, and constraints. Data Manipulation Language (DML) is used to manipulate the data within the database, including operations like inserting, updating, deleting, and querying data. Database administrators typically execute DDL statements, while application developers and end-users work with DML commands.

Source: [Geeks For Geeks](https://www.geeksforgeeks.org/difference-between-ddl-and-dml-in-dbms/)

## W10

What is physical data independence?

**Answer:**

Physical data independence means that changes to the physical storage or access methods of a database don't impact the logical structure or external applications accessing the data. This concept allows DBMS admin to fine-tune storage while keeping the logical view consistent for users and applications.

Source: [Geeks for Geeks](https://www.geeksforgeeks.org/physical-and-logical-data-independence/)

<hr style="height:2px;">

# Entity-Relationship Modeling

## Overview

The ability to understand a general description of a requested data model and to transform into a more precise, specified _logical model_ is one of the most important skills for using databases. SW and data engineers build applications and data models for end-users. The end-users, product managers and business managers are not SW or data modeling experts. They will express their _intent_ in imprecise, text and words.

The users and business stakeholder often can understand and interact using a _conceptual model_ but details like keys, foreign keys, ... are outside their scope.

In this problem, you will:
- Understand a short written description of a requested data model.
- Produce a _conceptual data model diagram_ using Lucidchart.
- Produce a _logical data model diagram_ using Lucidchart.

You can sign up for a free [Lucidchart account.](https://www.lucidchart.com/pages/landing) The free account provides the capabilities you will need for this course.

To draw the diagrams, you need to add the _entity relationship_ shapes. Lecture 2 demonstrated how to add the shapes.

| <img src="./lucidchart.jpg"> |
| :---: |
| __Adding Entity Relationship Shapes__|

We provide a simple [Lucidchart document](https://lucid.app/lucidchart/828777b1-7b2d-4828-bedb-37b6d456c33e/edit?invitationId=inv_a142899a-7e60-44e9-b18e-335d7c9767fc) from Lecture 2 that helps you get started. You need a Lucidchart account to access the document and diagrams.

## Data Model Description

The data model represents banks, customers. employees and accouts. The model has the following entity types/sets:
1. _Customer_
2. _Employee_ of the banking company
3. _Branch,_ which is a location of one of the banks offices
4. _Savings Account_
5. _Checking Account_
6. _Loan_
7. _Portfolio_


_Customer_ has the following properties:
- _customerID_
- _lastName_
- _firstName_
- _email_
- _dateOfBirth_


_Employee_ has the following properties:
- _employeeID_
- _lastName_
- _firstName_
- _jobTitle_


_Branch_ has the following properties:
- _branchID_
- _zipCode_


_Savings Account_ has the following properties:
- _accountID_
- _balance_
- _interestRate_


_Checking Account_ has the following properties:
- _accountID_
- _balance_


_Loan_ has the following properties.
- _loanID_
- _balance_
- _interestRate_


_Portfolio_ has the following properties:
- _portfolioID_
- _createdDate_

The data model has the following relationships:
- _Customer Branch_ connects a customer and a branch. A _Customer_ is connected to exactly one _Branch_. A _Branch_ may have 0, 1 or many customers.
- _Employee Branch_ connects an employee and a branch. An _Employee_ is connected to exactly one _Branch_. A _Branch_ may have 0, 1 or many associated employees.
- _Savings Account Branch_, _Checking Account Branch_, and _Loan Branch_ all have the same pattern.
    - An account/loan has exactly one branch.
    - A _Branch_ many have 0, 1 or many accounts/loans.
- _Savings Customer_, _Checking Customer_, _Loan Customer_, and _Portfolio Customer_ follow the same pattern. 
    - The account/loan has exactly one customer.
    - The customer may have 0 or 1 of each type of account.
- A _Portfolio_ is related to exactly one _Customer_, exactly one _Savings Account_, exactly one _Checking Account_, and exactly one _Loan_.
- _Portfolio Advisor_ relates a _Portfolio_ and _Employee_. An _Employee_ may be the advisor for 0, 1 or many _Portfolios_. A _Portfolio_ may have at most one _Employee_ advisor.

## Answer

1. Place your Logical Model diagram below.
2. You _may_ have to add attributes to entities to implement the model.
3. You _may_ make reasonable assumptions. Please document your assumptions below. You may add comments/notes to your diagram for clarity.

Assumptions:
1. The `accountId` attributes for Savings and Checking accounts are unique primary keys, not shared foreign keys 
2. Each Savings account, Checking account, and Loan can only be a part of one Portfolio, and only be owned by one person
3. All `ID` related attributes are completely unique, and operate as primary keys for all entities

ER Diagram:

Save your diagram to an image, place in the same directory as your notebook and change the file name in the HTML ```img``` tag in this Markdown cell.

| <img src="./HW1LogicalER.png"> |
| :---: |
| __Logical ER Diagram__|

# Relational Algebra

## R-1

The following is the SQL DDL for the `db_book.classroom` table.

```
CREATE TABLE IF NOT EXISTS db_book.classroom
(
    building    VARCHAR(15) NOT NULL,
    room_number VARCHAR(7)  NOT NULL,
    capacity    DECIMAL(4)  NULL,
    PRIMARY KEY (building, room_number)
);
```

Using the notation from the lecture slides, provide the corresponding relation schema definition.

**Answer:**

Branch (<ins>branchID</ins>, zipCode)

Customer (<ins>customerID</ins>, lastName, firstName, email, dateOfBirth, **branchID**)

Employee (<ins>employeeID</ins>, lastName, firstName, jobTitle, **branchID**)

Portfolio (<ins>portfolioID</ins>, createdDate, **customerID**, **employeeID**, **branchID**)

Savings Account (<ins>accountID</ins>, balance, interestRate, **customerID**, **portfolioID**, **branchID**)

Checking Account (<ins>accountID</ins>, balance, **customerID**,  **portfolioID**, **branchID**)

Loan (<ins>loanID</ins>, balance, interestRate, **customerID**,  **portfolioID**, **branchID**)

## Answer Format

For the answers to the relational algebra questions, you will use the [RelaX calculator](https://dbis-uibk.github.io/relax/calc/gist/4f7866c17624ca9dfa85ed2482078be8/relax-silberschatz-english.txt/0) with the schema associated with the book. You answer should include the algebra statement in as text and a screenshot of the execution result. Question __R0__ below shows a sample of that the answer will look like.

## R0

Write a relational algebra statement that produces a table of the following form:
- ID is the instructor ID
- name is the instructor name
- course_id, sec_id, semester, year of a section
- building, room_number

__Note:__
1. You will have to use the instructor, teaches and section relations
2. Your answer should only include sections taught in ```Comp. Sci.``` in ```2009```

Algebra statement:

```
π ID, name, course_id, sec_id, semester, year, building, room_number(
	(σ dept_name='Comp. Sci.' ∧ year=2009 
		(teaches ⨝ instructor)
		) 
⨝ section)
```

Execution:

| <img src="./R0-sample.jpg"> |
| :---: |
| __RO Execution Result__|

## R1

Write a relational algebra statement that produces a relation with the columns:

- `student.name`
- `student.dept_name`
- `student.tot_cred`
- `instructor.name` (the instructor that advises the student)
- `instructor.dept_name`

Only keep students who have earned more than 90 credits.

__Note:__
1. You will have to use the `student`, `instructor`, and `advisor` relations.
2. You should only include students that have an advisor, i.e., `instructor.name` and `instructor.dept_name` should be non-null for all rows.

Algebra statement:

```
π student.name, student.dept_name, student.tot_cred, instructor.name, instructor.dept_name (	
	σ instructor.ID = advisor.i_id (
		(instructor) 
		⨯ 
		(σ student.ID = advisor.s_id ∧ student.tot_cred > 90 (student x advisor))))

```

Execution:

| <img src="./HW1_R1_result.png"> |
| :---: |
| __R1 Execution Result__|

## R2

Write a relational algebra statement that produces a relation with the columns:

* `course_id`
* `title`
* `prereq_course_id`
* `prereq_course_title`

This relation represents courses and their prereqs.

__Note:__
1. This query requires the ```course``` and ```prereq``` tables.
2. Your answer should only include courses in the `Comp. Sci.` department.
2. If a course has no prereqs, `prereq_course_id` and `prereq_course_title` should both be *null*.
3. You _may_ have to use table and column renaming.

Algebra statement:

```
π course_id, title, prereq_course_id, prereq_course_title (
    (course)
    ⨝
    (σ prereq_id = prereq_course_id (
        (π course_id, prereq_id (prereq))
        ⨯
        (π prereq_course_id, prereq_course_title
            (ρ prereq_course_id <- course_id, prereq_course_title <- title (course))))))

```

Execution:

| <img src="./HW1_R2_result.png"> |
| :---: |
| __R2 Execution Result__|

# SQL

## New Database

[MySQL Tutorial](https://www.mysqltutorial.org/) is a good site with information that complements and extends the core material in our course. Much of the material the site covers is applicable to other SQL products. MySQL Tutorial uses an interesting dataset that is more complex than the simple "db_book" database. This is the [Classic Models Dataset](https://www.mysqltutorial.org/getting-started-with-mysql/mysql-sample-database/). The complexity allows us to better appreciate more complex SQL concepts.


You learned how to run a SQL script/file as part of HW0. **Use the same approach to load and create the ```Classic Models Database```.** The file is ```classic-models-database.sql``` and is in the HW1 folder. 


To test loading the data, you can use the cell below.

In [11]:
%sql show tables;

 * mysql+pymysql://root:***@localhost
8 rows affected.

[('customers',),
 ('employees',),
 ('offices',),
 ('orderdetails',),
 ('orders',),
 ('payments',),
 ('productlines',),
 ('products',)]

In [10]:
%sql USE classicmodels;

 * mysql+pymysql://root:***@localhost
0 rows affected.

[]

## SQL 1

This query uses `customers` and `employees`.

Write and execute a SQL query that produces a table with the following columns:

- `customerContactName`
- `customerPhone`
- `salesRepName`

Only keep customers from France. Order your output by `customerContactName`.

Notes:
- The names of your columns must match exactly with what is specified.
- `customerContactName` can be formed by combining `customers.contactFirstName` and `customers.contactLastName`.
- `salesRepName` can be formed by combining `employees.firstName` and `employees.lastName`.

In [17]:
%%sql
SELECT DISTINCT CONCAT(customers.contactFirstName, ' ', customers.contactLastName) AS customerContactName,
       customers.phone as customerPhone,
       CONCAT(employees.firstName, ' ', employees.lastName) AS salesRepName
FROM customers, employees
JOIN classicmodels.customers c on employees.employeeNumber = c.salesRepEmployeeNumber
WHERE customers.country = 'France'
ORDER BY customerContactName;

 * mysql+pymysql://root:***@localhost
180 rows affected.

[('Annette  Roulet', '61.77.6555', 'George Vanauf'),
 ('Annette  Roulet', '61.77.6555', 'Martin Gerard'),
 ('Annette  Roulet', '61.77.6555', 'Foon Yue Tseng'),
 ('Annette  Roulet', '61.77.6555', 'Loui Bondur'),
 ('Annette  Roulet', '61.77.6555', 'Gerard Hernandez'),
 ('Annette  Roulet', '61.77.6555', 'Leslie Jennings'),
 ('Annette  Roulet', '61.77.6555', 'Steve Patterson'),
 ('Annette  Roulet', '61.77.6555', 'Pamela Castillo'),
 ('Annette  Roulet', '61.77.6555', 'Mami Nishi'),
 ('Annette  Roulet', '61.77.6555', 'Larry Bott'),
 ('Annette  Roulet', '61.77.6555', 'Julie Firrelli'),
 ('Annette  Roulet', '61.77.6555', 'Barry Jones'),
 ('Annette  Roulet', '61.77.6555', 'Andy Fixter'),
 ('Annette  Roulet', '61.77.6555', 'Peter Marsh'),
 ('Annette  Roulet', '61.77.6555', 'Leslie Thompson'),
 ('Carine  Schmitt', '40.32.2555', 'Foon Yue Tseng'),
 ('Carine  Schmitt', '40.32.2555', 'Andy Fixter'),
 ('Carine  Schmitt', '40.32.2555', 'Peter Marsh'),
 ('Carine  Schmitt', '40.32.2555', 'Martin Gerard'),
 ('Carine  Schmitt', '40.32.2555', 'Leslie Thompson'),
 ('Carine  Schmitt', '40.32.2555', 'Barry Jones'),
 ('Carine  Schmitt', '40.32.2555', 'Leslie Jennings'),
 ('Carine  Schmitt', '40.32.2555', 'George Vanauf'),
 ('Carine  Schmitt', '40.32.2555', 'Larry Bott'),
 ('Carine  Schmitt', '40.32.2555', 'Julie Firrelli'),
 ('Carine  Schmitt', '40.32.2555', 'Pamela Castillo'),
 ('Carine  Schmitt', '40.32.2555', 'Mami Nishi'),
 ('Carine  Schmitt', '40.32.2555', 'Loui Bondur'),
 ('Carine  Schmitt', '40.32.2555', 'Steve Patterson'),
 ('Carine  Schmitt', '40.32.2555', 'Gerard Hernandez'),
 ('Daniel  Tonini', '30.59.8555', 'Barry Jones'),
 ('Daniel  Tonini', '30.59.8555', 'George Vanauf'),
 ('Daniel  Tonini', '30.59.8555', 'Peter Marsh'),
 ('Daniel  Tonini', '30.59.8555', 'Andy Fixter'),
 ('Daniel  Tonini', '30.59.8555', 'Julie Firrelli'),
 ('Daniel  Tonini', '30.59.8555', 'Loui Bondur'),
 ('Daniel  Tonini', '30.59.8555', 'Mami Nishi'),
 ('Daniel  Tonini', '30.59.8555', 'Leslie Thompson'),
 ('Daniel  Tonini', '30.59.8555', 'Foon Yue Tseng'),
 ('Daniel  Tonini', '30.59.8555', 'Leslie Jennings'),
 ('Daniel  Tonini', '30.59.8555', 'Larry Bott'),
 ('Daniel  Tonini', '30.59.8555', 'Steve Patterson'),
 ('Daniel  Tonini', '30.59.8555', 'Martin Gerard'),
 ('Daniel  Tonini', '30.59.8555', 'Pamela Castillo'),
 ('Daniel  Tonini', '30.59.8555', 'Gerard Hernandez'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Gerard Hernandez'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Leslie Jennings'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Steve Patterson'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Leslie Thompson'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Larry Bott'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Loui Bondur'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Mami Nishi'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Foon Yue Tseng'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Martin Gerard'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Julie Firrelli'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Barry Jones'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Andy Fixter'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'George Vanauf'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Peter Marsh'),
 ('Daniel Da Silva', '+33 1 46 62 7555', 'Pamela Castillo'),
 ('Dominique Perrier', '(1) 47.55.6555', 'George Vanauf'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Barry Jones'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Martin Gerard'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Mami Nishi'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Leslie Thompson'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Peter Marsh'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Andy Fixter'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Julie Firrelli'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Larry Bott'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Steve Patterson'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Pamela Castillo'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Leslie Jennings'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Loui Bondur'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Gerard Hernandez'),
 ('Dominique Perrier', '(1) 47.55.6555', 'Foon Yue Tseng'),
 ('Frédérique  Citeaux', '88.60.1555', 'Foon Yue Tseng'),
 ('Frédérique  Citeaux', '88.60.1555', 'Loui Bondur'),
 ('Frédérique  Citeaux', '88.60.1555', 'George Vanauf'),
 ('Frédérique  Citeaux', '88.60.1555', 'Martin Gerard'),
 ('Frédérique  Citeaux', '88.60.1555', 'Andy Fixter'),
 ('Frédérique  Citeaux', '88.60.1555', 'Barry Jones'),
 ('Frédérique  Citeaux', '88.60.1555', 'Leslie Jennings'),
 ('Frédérique  Citeaux', '88.60.1555', 'Julie Firrelli'),
 ('Frédérique  Citeaux', '88.60.1555', 'Gerard Hernandez'),
 ('Frédérique  Citeaux', '88.60.1555', 'Leslie Thompson'),
 ('Frédérique  Citeaux', '88.60.1555', 'Larry Bott'),
 ('Frédérique  Citeaux', '88.60.1555', 'Peter Marsh'),
 ('Frédérique  Citeaux', '88.60.1555', 'Steve Patterson'),
 ('Frédérique  Citeaux', '88.60.1555', 'Mami Nishi'),
 ('Frédérique  Citeaux', '88.60.1555', 'Pamela Castillo'),
 ('Janine  Labrune', '40.67.8555', 'Leslie Thompson'),
 ('Janine  Labrune', '40.67.8555', 'Martin Gerard'),
 ('Janine  Labrune', '40.67.8555', 'Barry Jones'),
 ('Janine  Labrune', '40.67.8555', 'Loui Bondur'),
 ('Janine  Labrune', '40.67.8555', 'Andy Fixter'),
 ('Janine  Labrune', '40.67.8555', 'Steve Patterson'),
 ('Janine  Labrune', '40.67.8555', 'Larry Bott'),
 ('Janine  Labrune', '40.67.8555', 'Mami Nishi'),
 ('Janine  Labrune', '40.67.8555', 'Gerard Hernandez'),
 ('Janine  Labrune', '40.67.8555', 'George Vanauf'),
 ('Janine  Labrune', '40.67.8555', 'Julie Firrelli'),
 ('Janine  Labrune', '40.67.8555', 'Peter Marsh'),
 ('Janine  Labrune', '40.67.8555', 'Foon Yue Tseng'),
 ('Janine  Labrune', '40.67.8555', 'Pamela Castillo'),
 ('Janine  Labrune', '40.67.8555', 'Leslie Jennings'),
 ('Laurence  Lebihan', '91.24.4555', 'Mami Nishi'),
 ('Laurence  Lebihan', '91.24.4555', 'Steve Patterson'),
 ('Laurence  Lebihan', '91.24.4555', 'Pamela Castillo'),
 ('Laurence  Lebihan', '91.24.4555', 'Larry Bott'),
 ('Laurence  Lebihan', '91.24.4555', 'Leslie Thompson'),
 ('Laurence  Lebihan', '91.24.4555', 'Peter Marsh'),
 ('Laurence  Lebihan', '91.24.4555', 'George Vanauf'),
 ('Laurence  Lebihan', '91.24.4555', 'Barry Jones'),
 ('Laurence  Lebihan', '91.24.4555', 'Martin Gerard'),
 ('Laurence  Lebihan', '91.24.4555', 'Julie Firrelli'),
 ('Laurence  Lebihan', '91.24.4555', 'Gerard Hernandez'),
 ('Laurence  Lebihan', '91.24.4555', 'Leslie Jennings'),
 ('Laurence  Lebihan', '91.24.4555', 'Loui Bondur'),
 ('Laurence  Lebihan', '91.24.4555', 'Foon Yue Tseng'),
 ('Laurence  Lebihan', '91.24.4555', 'Andy Fixter'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Pamela Castillo'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Peter Marsh'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Mami Nishi'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Steve Patterson'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Leslie Jennings'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Larry Bott'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Gerard Hernandez'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Foon Yue Tseng'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Julie Firrelli'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Leslie Thompson'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Barry Jones'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Andy Fixter'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Martin Gerard'),
 ('Marie Bertrand', '(1) 42.34.2555', 'George Vanauf'),
 ('Marie Bertrand', '(1) 42.34.2555', 'Loui Bondur'),
 ('Martine  Rancé', '20.16.1555', 'Barry Jones'),
 ('Martine  Rancé', '20.16.1555', 'Martin Gerard'),
 ('Martine  Rancé', '20.16.1555', 'Leslie Thompson'),
 ('Martine  Rancé', '20.16.1555', 'Loui Bondur'),
 ('Martine  Rancé', '20.16.1555', 'Steve Patterson'),
 ('Martine  Rancé', '20.16.1555', 'Andy Fixter'),
 ('Martine  Rancé', '20.16.1555', 'Gerard Hernandez'),
 ('Martine  Rancé', '20.16.1555', 'Mami Nishi'),
 ('Martine  Rancé', '20.16.1555', 'Leslie Jennings'),
 ('Martine  Rancé', '20.16.1555', 'Foon Yue Tseng'),
 ('Martine  Rancé', '20.16.1555', 'Pamela Castillo'),
 ('Martine  Rancé', '20.16.1555', 'George Vanauf'),
 ('Martine  Rancé', '20.16.1555', 'Larry Bott'),
 ('Martine  Rancé', '20.16.1555', 'Julie Firrelli'),
 ('Martine  Rancé', '20.16.1555', 'Peter Marsh'),
 ('Mary  Saveley', '78.32.5555', 'Julie Firrelli'),
 ('Mary  Saveley', '78.32.5555', 'Peter Marsh'),
 ('Mary  Saveley', '78.32.5555', 'Larry Bott'),
 ('Mary  Saveley', '78.32.5555', 'Foon Yue Tseng'),
 ('Mary  Saveley', '78.32.5555', 'George Vanauf'),
 ('Mary  Saveley', '78.32.5555', 'Pamela Castillo'),
 ('Mary  Saveley', '78.32.5555', 'Leslie Jennings'),
 ('Mary  Saveley', '78.32.5555', 'Mami Nishi'),
 ('Mary  Saveley', '78.32.5555', 'Gerard Hernandez'),
 ('Mary  Saveley', '78.32.5555', 'Andy Fixter'),
 ('Mary  Saveley', '78.32.5555', 'Steve Patterson'),
 ('Mary  Saveley', '78.32.5555', 'Loui Bondur'),
 ('Mary  Saveley', '78.32.5555', 'Barry Jones'),
 ('Mary  Saveley', '78.32.5555', 'Leslie Thompson'),
 ('Mary  Saveley', '78.32.5555', 'Martin Gerard'),
 ('Paul  Henriot', '26.47.1555', 'Larry Bott'),
 ('Paul  Henriot', '26.47.1555', 'Leslie Thompson'),
 ('Paul  Henriot', '26.47.1555', 'Mami Nishi'),
 ('Paul  Henriot', '26.47.1555', 'Peter Marsh'),
 ('Paul  Henriot', '26.47.1555', 'Barry Jones'),
 ('Paul  Henriot', '26.47.1555', 'Steve Patterson'),
 ('Paul  Henriot', '26.47.1555', 'Pamela Castillo'),
 ('Paul  Henriot', '26.47.1555', 'Julie Firrelli'),
 ('Paul  Henriot', '26.47.1555', 'Andy Fixter'),
 ('Paul  Henriot', '26.47.1555', 'Martin Gerard'),
 ('Paul  Henriot', '26.47.1555', 'Gerard Hernandez'),
 ('Paul  Henriot', '26.47.1555', 'Loui Bondur'),
 ('Paul  Henriot', '26.47.1555', 'Leslie Jennings'),
 ('Paul  Henriot', '26.47.1555', 'Foon Yue Tseng'),
 ('Paul  Henriot', '26.47.1555', 'George Vanauf')]

## SQL 2

This query uses `employees`, `customers`, `orders`, `orderdetails`.

Write and execute a SQL query that produces a table showing the amount of money each sales rep has generated.

Your table should have the following columns:

- `salesRepName`
- `moneyGenerated`

Order your output from greatest to least `moneyGenerated`.
    
Notes:
- The names of your columns must match exactly with what is specified.
- `salesRepName` can be formed by combining `employees.firstName` and `employees.lastName`.
- To calculate `moneyGenerated`:
    - Every order in `orders` is associated with multiple rows in `orderdetails`. The total amount of money spent on an order is the sum of `quantityOrdered * priceEach` for all the associated rows in `orderdetails`. **Only consider orders that are `Shipped`.**
    - A customer can have multiple orders. The total amount of money a customer has spent is the sum of the money spent on all that customer's orders.
    - A sales rep can have multiple customers. `moneyGenerated` is the sum of the money spent by all that sales rep's customers.
- You may find the [WITH keyword](https://www.tutorialspoint.com/mysql/mysql_with.htm) to be useful for cleaner code.

In [18]:
%%sql

SELECT CONCAT(e.firstName, ' ', e.lastName) AS salesRepName,
       SUM(od.quantityOrdered * od.priceEach) AS moneyGenerated
FROM employees e 
JOIN classicmodels.customers c on e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders o on c.customerNumber = o.customerNumber
JOIN orderdetails od on o.orderNumber = od.orderNumber
WHERE o.status = 'Shipped'
GROUP BY e.employeeNumber

 * mysql+pymysql://root:***@localhost
15 rows affected.

[('Steve Patterson', Decimal('449219.13')),
 ('Barry Jones', Decimal('637672.65')),
 ('Foon Yue Tseng', Decimal('488212.67')),
 ('Gerard Hernandez', Decimal('1065035.29')),
 ('Pamela Castillo', Decimal('790297.44')),
 ('George Vanauf', Decimal('584406.80')),
 ('Mami Nishi', Decimal('457110.07')),
 ('Larry Bott', Decimal('686653.25')),
 ('Leslie Jennings', Decimal('1021661.89')),
 ('Loui Bondur', Decimal('569485.75')),
 ('Martin Gerard', Decimal('387477.47')),
 ('Andy Fixter', Decimal('509385.82')),
 ('Leslie Thompson', Decimal('307952.43')),
 ('Peter Marsh', Decimal('523860.78')),
 ('Julie Firrelli', Decimal('386663.20'))]